// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/color.dart';
import 'api/db.dart';
import 'api/logger_bridge.dart';
import 'api/metadata.dart';
import 'api/music_cache.dart';
import 'api/runtime.dart';
import 'api/simple.dart';
import 'api/utils/base64.dart';
import 'api/utils/calculator.dart';
import 'api/utils/gif_decode.dart';
import 'api/utils/password.dart';
import 'api/utils/timestamp.dart';
import 'api/utils/uuid.dart';
import 'api/wifi_api/chat.dart';
import 'api/wifi_api/dict.dart';
import 'api/wifi_api/files.dart';
import 'api/wifi_api/ggtt.dart';
import 'api/wifi_api/init.dart';
import 'api/wifi_api/melatonin.dart';
import 'api/wifi_api/note.dart';
import 'api/wifi_api/song.dart';
import 'api/wifi_api/user.dart';
import 'api/wifi_api/webrtc.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:uuid/uuid.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiErrorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AudioMetadataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HashMapU8U8U8UsizePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ResultAudioMetadataStringPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ApiClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    dynamic raw,
  );

  @protected
  ApiError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    dynamic raw,
  );

  @protected
  AudioMetadata
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    dynamic raw,
  );

  @protected
  ResultAudioMetadataString
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    dynamic raw,
  );

  @protected
  Value
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  );

  @protected
  HashMapU8U8U8Usize
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    dynamic raw,
  );

  @protected
  DateTime dco_decode_Chrono_Local(dynamic raw);

  @protected
  Map<(int, int, int), BigInt> dco_decode_Map_record_u_8_u_8_u_8_usize_None(
    dynamic raw,
  );

  @protected
  ApiClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    dynamic raw,
  );

  @protected
  ApiError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    dynamic raw,
  );

  @protected
  AudioMetadata
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    dynamic raw,
  );

  @protected
  HashMapU8U8U8Usize
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    dynamic raw,
  );

  @protected
  ResultAudioMetadataString
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    dynamic raw,
  );

  @protected
  Value
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<GifFrameRgba> dco_decode_StreamSink_gif_frame_rgba_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  AllLyricsResponseForDart dco_decode_all_lyrics_response_for_dart(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Value
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GifFrame dco_decode_box_autoadd_gif_frame(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  (int, int, int) dco_decode_box_autoadd_record_u_8_u_8_u_8(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ColorInfo dco_decode_color_info(dynamic raw);

  @protected
  DirListingForDart dco_decode_dir_listing_for_dart(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileEntryForDart dco_decode_file_entry_for_dart(dynamic raw);

  @protected
  FileInfoForDart dco_decode_file_info_for_dart(dynamic raw);

  @protected
  GgttCode dco_decode_ggtt_code(dynamic raw);

  @protected
  GifFrame dco_decode_gif_frame(dynamic raw);

  @protected
  GifFrameRgba dco_decode_gif_frame_rgba(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageColorResult dco_decode_image_color_result(dynamic raw);

  @protected
  List<ResultAudioMetadataString>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FileEntryForDart> dco_decode_list_file_entry_for_dart(dynamic raw);

  @protected
  List<GifFrame> dco_decode_list_gif_frame(dynamic raw);

  @protected
  List<GifFrameRgba> dco_decode_list_gif_frame_rgba(dynamic raw);

  @protected
  List<ImageColorResult> dco_decode_list_image_color_result(dynamic raw);

  @protected
  List<LocalSong> dco_decode_list_local_song(dynamic raw);

  @protected
  List<MelatoninMovieListForDart> dco_decode_list_melatonin_movie_list_for_dart(
    dynamic raw,
  );

  @protected
  List<NoteSummary> dco_decode_list_note_summary(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<((int, int, int), BigInt)>
  dco_decode_list_record_record_u_8_u_8_u_8_usize(dynamic raw);

  @protected
  List<SongWithUrlForDart> dco_decode_list_song_with_url_for_dart(dynamic raw);

  @protected
  List<Word> dco_decode_list_word(dynamic raw);

  @protected
  List<WordHistory> dco_decode_list_word_history(dynamic raw);

  @protected
  LocalSong dco_decode_local_song(dynamic raw);

  @protected
  LoginResponse dco_decode_login_response(dynamic raw);

  @protected
  MelatoninMovieDetailForDart dco_decode_melatonin_movie_detail_for_dart(
    dynamic raw,
  );

  @protected
  MelatoninMovieListForDart dco_decode_melatonin_movie_list_for_dart(
    dynamic raw,
  );

  @protected
  NoteSummary dco_decode_note_summary(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Value?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  );

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  GifFrame? dco_decode_opt_box_autoadd_gif_frame(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PaginatedResponseForDart dco_decode_paginated_response_for_dart(dynamic raw);

  @protected
  ((int, int, int), BigInt) dco_decode_record_record_u_8_u_8_u_8_usize(
    dynamic raw,
  );

  @protected
  (int, int, int) dco_decode_record_u_8_u_8_u_8(dynamic raw);

  @protected
  SongPaginatedResponseForDart dco_decode_song_paginated_response_for_dart(
    dynamic raw,
  );

  @protected
  SongWithUrlForDart dco_decode_song_with_url_for_dart(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserSettings dco_decode_user_settings(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Word dco_decode_word(dynamic raw);

  @protected
  WordHistory dco_decode_word_history(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ApiClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    SseDeserializer deserializer,
  );

  @protected
  ApiError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    SseDeserializer deserializer,
  );

  @protected
  AudioMetadata
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    SseDeserializer deserializer,
  );

  @protected
  ResultAudioMetadataString
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    SseDeserializer deserializer,
  );

  @protected
  Value
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  );

  @protected
  HashMapU8U8U8Usize
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    SseDeserializer deserializer,
  );

  @protected
  DateTime sse_decode_Chrono_Local(SseDeserializer deserializer);

  @protected
  Map<(int, int, int), BigInt> sse_decode_Map_record_u_8_u_8_u_8_usize_None(
    SseDeserializer deserializer,
  );

  @protected
  ApiClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    SseDeserializer deserializer,
  );

  @protected
  ApiError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    SseDeserializer deserializer,
  );

  @protected
  AudioMetadata
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    SseDeserializer deserializer,
  );

  @protected
  HashMapU8U8U8Usize
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    SseDeserializer deserializer,
  );

  @protected
  ResultAudioMetadataString
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    SseDeserializer deserializer,
  );

  @protected
  Value
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<GifFrameRgba> sse_decode_StreamSink_gif_frame_rgba_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  AllLyricsResponseForDart sse_decode_all_lyrics_response_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Value
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GifFrame sse_decode_box_autoadd_gif_frame(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  (int, int, int) sse_decode_box_autoadd_record_u_8_u_8_u_8(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ColorInfo sse_decode_color_info(SseDeserializer deserializer);

  @protected
  DirListingForDart sse_decode_dir_listing_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileEntryForDart sse_decode_file_entry_for_dart(SseDeserializer deserializer);

  @protected
  FileInfoForDart sse_decode_file_info_for_dart(SseDeserializer deserializer);

  @protected
  GgttCode sse_decode_ggtt_code(SseDeserializer deserializer);

  @protected
  GifFrame sse_decode_gif_frame(SseDeserializer deserializer);

  @protected
  GifFrameRgba sse_decode_gif_frame_rgba(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageColorResult sse_decode_image_color_result(SseDeserializer deserializer);

  @protected
  List<ResultAudioMetadataString>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FileEntryForDart> sse_decode_list_file_entry_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  List<GifFrame> sse_decode_list_gif_frame(SseDeserializer deserializer);

  @protected
  List<GifFrameRgba> sse_decode_list_gif_frame_rgba(
    SseDeserializer deserializer,
  );

  @protected
  List<ImageColorResult> sse_decode_list_image_color_result(
    SseDeserializer deserializer,
  );

  @protected
  List<LocalSong> sse_decode_list_local_song(SseDeserializer deserializer);

  @protected
  List<MelatoninMovieListForDart> sse_decode_list_melatonin_movie_list_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  List<NoteSummary> sse_decode_list_note_summary(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<((int, int, int), BigInt)>
  sse_decode_list_record_record_u_8_u_8_u_8_usize(SseDeserializer deserializer);

  @protected
  List<SongWithUrlForDart> sse_decode_list_song_with_url_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  List<Word> sse_decode_list_word(SseDeserializer deserializer);

  @protected
  List<WordHistory> sse_decode_list_word_history(SseDeserializer deserializer);

  @protected
  LocalSong sse_decode_local_song(SseDeserializer deserializer);

  @protected
  LoginResponse sse_decode_login_response(SseDeserializer deserializer);

  @protected
  MelatoninMovieDetailForDart sse_decode_melatonin_movie_detail_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  MelatoninMovieListForDart sse_decode_melatonin_movie_list_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  NoteSummary sse_decode_note_summary(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Value?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GifFrame? sse_decode_opt_box_autoadd_gif_frame(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PaginatedResponseForDart sse_decode_paginated_response_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  ((int, int, int), BigInt) sse_decode_record_record_u_8_u_8_u_8_usize(
    SseDeserializer deserializer,
  );

  @protected
  (int, int, int) sse_decode_record_u_8_u_8_u_8(SseDeserializer deserializer);

  @protected
  SongPaginatedResponseForDart sse_decode_song_paginated_response_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  SongWithUrlForDart sse_decode_song_with_url_for_dart(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserSettings sse_decode_user_settings(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Word sse_decode_word(SseDeserializer deserializer);

  @protected
  WordHistory sse_decode_word_history(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    ApiClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    ApiError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    AudioMetadata self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    ResultAudioMetadataString self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    HashMapU8U8U8Usize self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Chrono_Local(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_Map_record_u_8_u_8_u_8_usize_None(
    Map<(int, int, int), BigInt> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    ApiClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    ApiError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    AudioMetadata self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    HashMapU8U8U8Usize self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    ResultAudioMetadataString self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_gif_frame_rgba_Sse(
    RustStreamSink<GifFrameRgba> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_all_lyrics_response_for_dart(
    AllLyricsResponseForDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_gif_frame(
    GifFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_u_8_u_8_u_8(
    (int, int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_color_info(ColorInfo self, SseSerializer serializer);

  @protected
  void sse_encode_dir_listing_for_dart(
    DirListingForDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_entry_for_dart(
    FileEntryForDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_info_for_dart(
    FileInfoForDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ggtt_code(GgttCode self, SseSerializer serializer);

  @protected
  void sse_encode_gif_frame(GifFrame self, SseSerializer serializer);

  @protected
  void sse_encode_gif_frame_rgba(GifFrameRgba self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_color_result(
    ImageColorResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    List<ResultAudioMetadataString> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_entry_for_dart(
    List<FileEntryForDart> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gif_frame(List<GifFrame> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gif_frame_rgba(
    List<GifFrameRgba> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_image_color_result(
    List<ImageColorResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_song(
    List<LocalSong> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_melatonin_movie_list_for_dart(
    List<MelatoninMovieListForDart> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_summary(
    List<NoteSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_record_u_8_u_8_u_8_usize(
    List<((int, int, int), BigInt)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_song_with_url_for_dart(
    List<SongWithUrlForDart> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_word(List<Word> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_history(
    List<WordHistory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_song(LocalSong self, SseSerializer serializer);

  @protected
  void sse_encode_login_response(LoginResponse self, SseSerializer serializer);

  @protected
  void sse_encode_melatonin_movie_detail_for_dart(
    MelatoninMovieDetailForDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_melatonin_movie_list_for_dart(
    MelatoninMovieListForDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_summary(NoteSummary self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_gif_frame(
    GifFrame? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_paginated_response_for_dart(
    PaginatedResponseForDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_record_u_8_u_8_u_8_usize(
    ((int, int, int), BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_8_u_8_u_8(
    (int, int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_paginated_response_for_dart(
    SongPaginatedResponseForDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_with_url_for_dart(
    SongWithUrlForDart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_settings(UserSettings self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_word(Word self, SseSerializer serializer);

  @protected
  void sse_encode_word_history(WordHistory self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiClient(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioMetadata(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapu8u8u8usize(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerResultAudioMetadataString(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    int ptr,
  );
}
