// Typed wrappers for WASM functions.
// wasm.d.ts is auto-generated by wasm-pack and returns Promise<any>.
// This file re-exports with concrete types. Import from here instead of '../src-wasm/pkg' directly.
//
// Usage:
//   import { list_videos_wasm, scan_videos_wasm } from '@/types/wasm-typed';
//   const result = await list_videos_wasm(null, 1, 50); // result is PaginatedResponse<VideoItem>

import * as wasm from '../src-wasm/pkg';
import type {
  PaginatedResponse,
  SongWithUrl,
  LyricsResponse,
  AllLyricsResponse,
  VideoItem,
  ImageItem,
  DirListing,
  UserItem,
  UserDirectory,
  MediaPathItem,
  ShortNote,
  WordHistory,
  Word,
  GgttResult,
  OpenAiSession,
  OpenAiMessage,
  ClipboardEntry,
} from './models';

// === 歌曲 ===
export const scan_songs_wasm = (): Promise<void> => wasm.scan_songs_wasm() as any;
export const get_all_songs_wasm = (page?: number | null, page_size?: number | null): Promise<PaginatedResponse<SongWithUrl>> => wasm.get_all_songs_wasm(page, page_size) as any;
export const get_songs_by_album_wasm = (album: string): Promise<SongWithUrl[]> => wasm.get_songs_by_album_wasm(album) as any;
export const get_songs_by_artist_wasm = (artist: string): Promise<SongWithUrl[]> => wasm.get_songs_by_artist_wasm(artist) as any;
export const get_song_cover_wasm = (song_id: string): Promise<string | null> => wasm.get_song_cover_wasm(song_id) as any;
export const get_song_file_wasm = (song_id: string): Promise<Uint8Array | null> => wasm.get_song_file_wasm(song_id) as any;
export const get_song_lyrics_wasm = (song_id: string): Promise<LyricsResponse> => wasm.get_song_lyrics_wasm(song_id) as any;
export const get_song_ttml_wasm = (song_id: string): Promise<string | null> => wasm.get_song_ttml_wasm(song_id) as any;
export const get_all_lyrics_wasm = (song_id: string): Promise<AllLyricsResponse> => wasm.get_all_lyrics_wasm(song_id) as any;
export const load_song_audio_zc = (song_id: string): Promise<[number, number]> => wasm.load_song_audio_zc(song_id) as any;

// === 视频 ===
export const scan_videos_wasm = (): Promise<void> => wasm.scan_videos_wasm() as any;
export const list_videos_wasm = (folder?: string | null, page?: number | null, page_size?: number | null): Promise<PaginatedResponse<VideoItem>> => wasm.list_videos_wasm(folder, page, page_size) as any;

// === 图片 ===
export const scan_images_wasm = (): Promise<void> => wasm.scan_images_wasm() as any;
export const get_image_folders_wasm = (): Promise<string[]> => wasm.get_image_folders_wasm() as any;
export const list_images_wasm = (folder?: string | null, page?: number | null, page_size?: number | null): Promise<PaginatedResponse<ImageItem>> => wasm.list_images_wasm(folder, page, page_size) as any;

// === 文件 ===
export const list_files_wasm = (path: string, page?: number | null, page_size?: number | null): Promise<DirListing> => wasm.list_files_wasm(path, page, page_size) as any;
export const get_file_info_wasm = (path: string): Promise<any> => wasm.get_file_info_wasm(path);
export const get_file_url_wasm = (path: string): string => wasm.get_file_url_wasm(path);
export const generate_tree_wasm = (path: string): Promise<{ success: boolean; file_path: string; filename: string }> => wasm.generate_tree_wasm(path) as any;

// === 用户/目录管理 ===
export const list_users_wasm = (): Promise<UserItem[]> => wasm.list_users_wasm() as any;
export const list_user_directories_wasm = (username?: string | null): Promise<UserDirectory[]> => wasm.list_user_directories_wasm(username) as any;
export const add_user_directory_wasm = (path: string, label?: string | null, allow_list?: string | null): Promise<UserDirectory> => wasm.add_user_directory_wasm(path, label, allow_list) as any;
export const delete_user_directory_wasm = (dir_id: string): Promise<void> => wasm.delete_user_directory_wasm(dir_id) as any;

// === 媒体路径 ===
export const list_media_paths_wasm = (media_type?: string | null): Promise<MediaPathItem[]> => wasm.list_media_paths_wasm(media_type) as any;
export const add_media_path_wasm = (directory_id: string, media_type: string, path: string, label?: string | null): Promise<MediaPathItem> => wasm.add_media_path_wasm(directory_id, media_type, path, label) as any;
export const delete_media_path_wasm = (path_id: string): Promise<void> => wasm.delete_media_path_wasm(path_id) as any;

// === 短笔记 ===
export const list_short_notes_wasm = (page?: number | null, page_size?: number | null): Promise<PaginatedResponse<ShortNote>> => wasm.list_short_notes_wasm(page, page_size) as any;
export const get_short_note_wasm = (id: string): Promise<ShortNote> => wasm.get_short_note_wasm(id) as any;
export const create_short_note_wasm = (content?: string | null, view_name?: string | null): Promise<ShortNote> => wasm.create_short_note_wasm(content, view_name) as any;
export const update_short_note_wasm = (id: string, content?: string | null, view_name?: string | null): Promise<ShortNote> => wasm.update_short_note_wasm(id, content, view_name) as any;
export const delete_short_note_wasm = (id: string): Promise<void> => wasm.delete_short_note_wasm(id) as any;

// === 笔记 ===
export const list_notes_wasm = (page?: number | null, limit?: number | null): Promise<any> => wasm.list_notes_wasm(page, limit);
export const get_note_wasm = (uuid: string): Promise<any> => wasm.get_note_wasm(uuid);
export const save_note_wasm = (id: string | null | undefined, text: string, filename?: string | null): Promise<any> => wasm.save_note_wasm(id, text, filename);
export const create_note_wasm = (text: string, filename?: string | null): Promise<any> => wasm.create_note_wasm(text, filename);
export const search_notes_wasm = (query: string): Promise<any> => wasm.search_notes_wasm(query);

// === 词典/搜索 ===
export const search_xiandaihanyu = (word: string): Promise<string> => wasm.search_xiandaihanyu(word) as any;
export const search_collins = (word: string): Promise<string> => wasm.search_collins(word) as any;
export const search_ldoce = (word: string): Promise<string> => wasm.search_ldoce(word) as any;
export const chinese_dict = (word: string): Promise<string> => wasm.chinese_dict(word) as any;
export const search_ggtt = (code: string): Promise<GgttResult> => wasm.search_ggtt(code) as any;
export const get_recent_history = (limit: bigint): Promise<{ msg: string; data: WordHistory[] }> => wasm.get_recent_history(limit) as any;
export const get_top_words = (): Promise<{ msg: string; data: Word[] }> => wasm.get_top_words() as any;

// === AI 对话 ===
export const create_session = (title: string): Promise<OpenAiSession> => wasm.create_session(title) as any;
export const list_sessions = (): Promise<OpenAiSession[]> => wasm.list_sessions() as any;
export const get_session = (session_id: string): Promise<OpenAiSession> => wasm.get_session(session_id) as any;
export const delete_session = (session_id: string): Promise<void> => wasm.delete_session(session_id) as any;
export const add_message = (session_id: string, role: string, content: string, think?: string | null, cite?: string | null): Promise<OpenAiMessage> => wasm.add_message(session_id, role, content, think, cite) as any;
export const get_session_messages = (session_id: string): Promise<OpenAiMessage[]> => wasm.get_session_messages(session_id) as any;
export const chat_completion = (request: string): Promise<any> => wasm.chat_completion(request);
export const chat_completion_stream = (request: string): Promise<any> => wasm.chat_completion_stream(request);

// === 聊天 ===
export const send_message_wasm = (content: string): Promise<any> => wasm.send_message_wasm(content);
export const get_messages_wasm = (after?: string | null): Promise<any> => wasm.get_messages_wasm(after);
export const get_recent_contacts_wasm = (): Promise<any> => wasm.get_recent_contacts_wasm();
export const get_contacts_wasm = (): Promise<any> => wasm.get_contacts_wasm();
export const connect_chat_ws = (path: string, onMessage: (text: string) => void): WebSocket => wasm.connect_chat_ws(path, onMessage);

// === 登录 ===
export const login_wasm = (username: string, password: string, token?: string | null, port?: string | null): Promise<{ token: string; token_type: string }> => wasm.login_wasm(username, password, token, port) as any;

// === 基础设施 ===
export const init_api = wasm.init_api;
export const set_api_port = wasm.set_api_port;
export const get_base_url_wasm = wasm.get_base_url_wasm;
export const get_wasm_memory = wasm.get_wasm_memory;

// === 工具 ===
export const base64_encode_wasm = wasm.base64_encode_wasm;
export const base64_decode_wasm = wasm.base64_decode_wasm;
export const generate_uuid_v4 = wasm.generate_uuid_v4;
export const generate_uuid_v5 = wasm.generate_uuid_v5;
export const generate_uuid_v6 = wasm.generate_uuid_v6;
export const generate_uuid_v7 = wasm.generate_uuid_v7;
export const validate_uuid = wasm.validate_uuid;
export const generate_password = wasm.generate_password;
export const generate_strong_password = wasm.generate_strong_password;
export const get_current_local_time = wasm.get_current_local_time;
export const get_current_timestamp = wasm.get_current_timestamp;
export const get_current_utc_time = wasm.get_current_utc_time;
export const timestamp_to_local = wasm.timestamp_to_local;
export const timestamp_to_utc = wasm.timestamp_to_utc;
export const local_to_timestamp = wasm.local_to_timestamp;

// === 图片转换 ===
export const detect_image_format = wasm.detect_image_format;
export const convert_image_wasm = wasm.convert_image_wasm;
export const convert_image_with_size_wasm = wasm.convert_image_with_size_wasm;
export const crop_image_wasm = wasm.crop_image_wasm;
export const resize_image_wasm = wasm.resize_image_wasm;

// === QR 码 ===
export const generate_qr_png_wasm = wasm.generate_qr_png_wasm;
export const generate_qr_unicode_wasm = wasm.generate_qr_unicode_wasm;
export const qr_info_wasm = wasm.qr_info_wasm;

// === zici ===
export const get_new_chars = wasm.get_new_chars;
export const get_new_words = wasm.get_new_words;
export const get_words_data = wasm.get_words_data;
export const get_word_count = wasm.get_word_count;
export const get_entry_size = wasm.get_entry_size;
export const get_explanation_for_word = wasm.get_explanation_for_word;
export const get_direction = wasm.get_direction;
export const my_console_log = wasm.my_console_log;

// === 剪贴板 ===
export const get_clipboard_history_wasm = (count?: number | null, type_filter?: string | null, search?: string | null): Promise<ClipboardEntry[]> =>
  wasm.get_clipboard_history_wasm(count, type_filter, search) as any;
