// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Connect to the chat WebSocket and stream messages to Dart.
/// The stream ends when the Dart side cancels the subscription.
Stream<String> connectChatWs({required String path}) =>
    RustLib.instance.api.crateApiWifiApiChatConnectChatWs(path: path);
