// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<ClipboardEntry>> getClipboardHistoryForDart({
  PlatformInt64? count,
  String? typeFilter,
  String? search,
}) => RustLib.instance.api.crateApiWifiApiClipboardGetClipboardHistoryForDart(
  count: count,
  typeFilter: typeFilter,
  search: search,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiError>>
abstract class ApiError implements RustOpaqueInterface {}

class ClipboardEntry {
  final PlatformInt64 id;
  final String entryType;
  final String? textContent;
  final String contentHash;
  final String createdAt;
  final String? imageUrl;
  final String? imagePath;

  const ClipboardEntry({
    required this.id,
    required this.entryType,
    this.textContent,
    required this.contentHash,
    required this.createdAt,
    this.imageUrl,
    this.imagePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entryType.hashCode ^
      textContent.hashCode ^
      contentHash.hashCode ^
      createdAt.hashCode ^
      imageUrl.hashCode ^
      imagePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipboardEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entryType == other.entryType &&
          textContent == other.textContent &&
          contentHash == other.contentHash &&
          createdAt == other.createdAt &&
          imageUrl == other.imageUrl &&
          imagePath == other.imagePath;
}
