// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'clipboard.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<String> searchXianzaihanyuForDart({required String word}) => RustLib
    .instance
    .api
    .crateApiWifiApiDictSearchXianzaihanyuForDart(word: word);

Future<String> searchCollinsForDart({required String word}) =>
    RustLib.instance.api.crateApiWifiApiDictSearchCollinsForDart(word: word);

Future<Uint8List> collinsResourceForDart({required String resourcePath}) =>
    RustLib.instance.api.crateApiWifiApiDictCollinsResourceForDart(
      resourcePath: resourcePath,
    );

Future<String> searchLdoceForDart({required String word}) =>
    RustLib.instance.api.crateApiWifiApiDictSearchLdoceForDart(word: word);

Future<Uint8List> ldoceResourceForDart({required String resourcePath}) =>
    RustLib.instance.api.crateApiWifiApiDictLdoceResourceForDart(
      resourcePath: resourcePath,
    );

Future<Uint8List> xiandaihanyuResourceForDart({required String resourcePath}) =>
    RustLib.instance.api.crateApiWifiApiDictXiandaihanyuResourceForDart(
      resourcePath: resourcePath,
    );

Future<List<WordHistory>> getRecentHistoryForDart({
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiWifiApiDictGetRecentHistoryForDart(
  limit: limit,
);

Future<List<Word>> getTopWordsForDart() =>
    RustLib.instance.api.crateApiWifiApiDictGetTopWordsForDart();

class Word {
  final UuidValue id;
  final String word;
  final int hasSearchedTimes;

  const Word({
    required this.id,
    required this.word,
    required this.hasSearchedTimes,
  });

  @override
  int get hashCode => id.hashCode ^ word.hashCode ^ hasSearchedTimes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Word &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          word == other.word &&
          hasSearchedTimes == other.hasSearchedTimes;
}

class WordHistory {
  final UuidValue id;
  final String word;
  final DateTime time;
  final DateTime createdAt;

  const WordHistory({
    required this.id,
    required this.word,
    required this.time,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ word.hashCode ^ time.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordHistory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          word == other.word &&
          time == other.time &&
          createdAt == other.createdAt;
}
