// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'clipboard.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FileEntry`

Future<DirListingForDart> listFilesForDart({
  required String path,
  int? page,
  int? pageSize,
}) => RustLib.instance.api.crateApiWifiApiFilesListFilesForDart(
  path: path,
  page: page,
  pageSize: pageSize,
);

Future<FileInfoForDart> getFileInfoForDart({required String path}) =>
    RustLib.instance.api.crateApiWifiApiFilesGetFileInfoForDart(path: path);

Future<String> getFileUrlForDart({required String path}) =>
    RustLib.instance.api.crateApiWifiApiFilesGetFileUrlForDart(path: path);

class DirListingForDart {
  final String path;
  final List<FileEntryForDart> entries;
  final PlatformInt64 total;

  const DirListingForDart({
    required this.path,
    required this.entries,
    required this.total,
  });

  @override
  int get hashCode => path.hashCode ^ entries.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirListingForDart &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          entries == other.entries &&
          total == other.total;
}

class FileEntryForDart {
  final String name;
  final String path;
  final bool isDir;
  final BigInt size;
  final String? lastModified;

  const FileEntryForDart({
    required this.name,
    required this.path,
    required this.isDir,
    required this.size,
    this.lastModified,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntryForDart &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          size == other.size &&
          lastModified == other.lastModified;
}

class FileInfoForDart {
  final String name;
  final String path;
  final bool isDir;
  final BigInt size;
  final String? lastModified;
  final String contentType;

  const FileInfoForDart({
    required this.name,
    required this.path,
    required this.isDir,
    required this.size,
    this.lastModified,
    required this.contentType,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      lastModified.hashCode ^
      contentType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileInfoForDart &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          size == other.size &&
          lastModified == other.lastModified &&
          contentType == other.contentType;
}
