// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'dict.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SearchRequest`

Future<GgttCode> searchGgttCodeForDart({required String search}) => RustLib
    .instance
    .api
    .crateApiWifiApiGgttSearchGgttCodeForDart(search: search);

class GgttCode {
  final int id;
  final String char;
  final String code86;
  final bool hasDiagram;
  final String? svg1;
  final String? svg2;
  final String? svg3;
  final String? svg4;

  const GgttCode({
    required this.id,
    required this.char,
    required this.code86,
    required this.hasDiagram,
    this.svg1,
    this.svg2,
    this.svg3,
    this.svg4,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      char.hashCode ^
      code86.hashCode ^
      hasDiagram.hashCode ^
      svg1.hashCode ^
      svg2.hashCode ^
      svg3.hashCode ^
      svg4.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GgttCode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          char == other.char &&
          code86 == other.code86 &&
          hasDiagram == other.hasDiagram &&
          svg1 == other.svg1 &&
          svg2 == other.svg2 &&
          svg3 == other.svg3 &&
          svg4 == other.svg4;
}
