// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `with_client`, `with_http_client`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GLOBAL_CLIENT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

/// 初始化API客户端
/// Flutter在启动时调用此函数来初始化一个可变的reqwest客户端
///
/// # 参数
/// - `token`: 可选的认证令牌
/// - `port`: 服务器端口号，如果为None则使用默认端口23001
Future<void> initClient({String? token, int? port}) => RustLib.instance.api
    .crateApiWifiApiInitInitClient(token: token, port: port);

/// 设置API客户端的基础URL
Future<void> setClientBaseUrl({required String baseUrl}) =>
    RustLib.instance.api.crateApiWifiApiInitSetClientBaseUrl(baseUrl: baseUrl);

/// 设置API客户端的token
Future<void> setClientToken({required String token}) =>
    RustLib.instance.api.crateApiWifiApiInitSetClientToken(token: token);

/// 清除API客户端的token
Future<void> clearClientToken() =>
    RustLib.instance.api.crateApiWifiApiInitClearClientToken();

/// 获取API客户端的基础URL
Future<String> getClientBaseUrl() =>
    RustLib.instance.api.crateApiWifiApiInitGetClientBaseUrl();

/// 获取全局API客户端的克隆
/// 这样就可以直接传递给像`get_top_words_for_dart(&client)`这样的函数
Future<ApiClient> getClientClone() =>
    RustLib.instance.api.crateApiWifiApiInitGetClientClone();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiClient>>
abstract class ApiClient implements RustOpaqueInterface {}
