// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'dict.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActorMovieQuery`, `MelatoninListQuery`

Future<PaginatedResponseForDart> getMelatoninMoviesForDart({
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiWifiApiMelatoninGetMelatoninMoviesForDart(
  page: page,
  pageSize: pageSize,
);

Future<PaginatedResponseForDart> getMoviesByActorForDart({
  required String actor,
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiWifiApiMelatoninGetMoviesByActorForDart(
  actor: actor,
  page: page,
  pageSize: pageSize,
);

Future<PaginatedResponseForDart> getMoviesByGenreForDart({
  required String genre,
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiWifiApiMelatoninGetMoviesByGenreForDart(
  genre: genre,
  page: page,
  pageSize: pageSize,
);

Future<MelatoninMovieDetailForDart> getMelatoninMovieByIdForDart({
  required UuidValue id,
}) => RustLib.instance.api.crateApiWifiApiMelatoninGetMelatoninMovieByIdForDart(
  id: id,
);

Future<List<String>> getBtListForDart({required UuidValue id}) =>
    RustLib.instance.api.crateApiWifiApiMelatoninGetBtListForDart(id: id);

class MelatoninMovieDetailForDart {
  final UuidValue id;
  final String title;
  final String coverPath;
  final List<String> videoPaths;
  final String? coverUrl;
  final List<String> videoUrls;
  final String nfoJson;
  final List<String> previewUrls;

  const MelatoninMovieDetailForDart({
    required this.id,
    required this.title,
    required this.coverPath,
    required this.videoPaths,
    this.coverUrl,
    required this.videoUrls,
    required this.nfoJson,
    required this.previewUrls,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      coverPath.hashCode ^
      videoPaths.hashCode ^
      coverUrl.hashCode ^
      videoUrls.hashCode ^
      nfoJson.hashCode ^
      previewUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MelatoninMovieDetailForDart &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          coverPath == other.coverPath &&
          videoPaths == other.videoPaths &&
          coverUrl == other.coverUrl &&
          videoUrls == other.videoUrls &&
          nfoJson == other.nfoJson &&
          previewUrls == other.previewUrls;
}

class MelatoninMovieListForDart {
  final UuidValue id;
  final String title;
  final String coverPath;
  final List<String> videoPaths;
  final String? coverUrl;
  final List<String> videoUrls;

  const MelatoninMovieListForDart({
    required this.id,
    required this.title,
    required this.coverPath,
    required this.videoPaths,
    this.coverUrl,
    required this.videoUrls,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      coverPath.hashCode ^
      videoPaths.hashCode ^
      coverUrl.hashCode ^
      videoUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MelatoninMovieListForDart &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          coverPath == other.coverPath &&
          videoPaths == other.videoPaths &&
          coverUrl == other.coverUrl &&
          videoUrls == other.videoUrls;
}

class PaginatedResponseForDart {
  final List<MelatoninMovieListForDart> data;
  final PlatformInt64 total;
  final int page;
  final int pageSize;
  final PlatformInt64 totalPages;

  const PaginatedResponseForDart({
    required this.data,
    required this.total,
    required this.page,
    required this.pageSize,
    required this.totalPages,
  });

  @override
  int get hashCode =>
      data.hashCode ^
      total.hashCode ^
      page.hashCode ^
      pageSize.hashCode ^
      totalPages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaginatedResponseForDart &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          total == other.total &&
          page == other.page &&
          pageSize == other.pageSize &&
          totalPages == other.totalPages;
}
