// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'dict.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CreateNoteResponse`, `SaveNoteResponse`

Future<NoteSummary> getNoteForDart({required String id}) =>
    RustLib.instance.api.crateApiWifiApiNoteGetNoteForDart(id: id);

Future<List<NoteSummary>> listNotesForDart({
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiWifiApiNoteListNotesForDart(
  page: page,
  pageSize: pageSize,
);

Future<NoteSummary> createNoteForDart({
  required String text,
  String? filename,
}) => RustLib.instance.api.crateApiWifiApiNoteCreateNoteForDart(
  text: text,
  filename: filename,
);

Future<NoteSummary> saveNoteForDart({
  required String id,
  required String text,
  String? filename,
}) => RustLib.instance.api.crateApiWifiApiNoteSaveNoteForDart(
  id: id,
  text: text,
  filename: filename,
);

Future<List<NoteSummary>> searchNotesForDart({required String query}) =>
    RustLib.instance.api.crateApiWifiApiNoteSearchNotesForDart(query: query);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Value>>
abstract class Value implements RustOpaqueInterface {}

class NoteSummary {
  final UuidValue id;
  final String? text;
  final String? simpleText;
  final String? filepath;
  final String? filename;
  final Value? fileInfo;
  final DateTime createdAt;
  final DateTime updatedAt;
  final String? sha256;

  const NoteSummary({
    required this.id,
    this.text,
    this.simpleText,
    this.filepath,
    this.filename,
    this.fileInfo,
    required this.createdAt,
    required this.updatedAt,
    this.sha256,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      simpleText.hashCode ^
      filepath.hashCode ^
      filename.hashCode ^
      fileInfo.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          simpleText == other.simpleText &&
          filepath == other.filepath &&
          filename == other.filename &&
          fileInfo == other.fileInfo &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          sha256 == other.sha256;
}
