// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'dict.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<SongPaginatedResponseForDart> getAllSongsForDart({
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiWifiApiSongGetAllSongsForDart(
  page: page,
  pageSize: pageSize,
);

Future<Uint8List> getSongFileForDart({required UuidValue songId}) =>
    RustLib.instance.api.crateApiWifiApiSongGetSongFileForDart(songId: songId);

Future<AllLyricsResponseForDart> getSongLyricsForDart({
  required UuidValue songId,
}) => RustLib.instance.api.crateApiWifiApiSongGetSongLyricsForDart(
  songId: songId,
);

class AllLyricsResponseForDart {
  final UuidValue songId;
  final String title;
  final String? artist;
  final String? lrc;
  final String? ttml;
  final String? eslrc;
  final String? qrc;
  final String? yrc;
  final String? lys;

  const AllLyricsResponseForDart({
    required this.songId,
    required this.title,
    this.artist,
    this.lrc,
    this.ttml,
    this.eslrc,
    this.qrc,
    this.yrc,
    this.lys,
  });

  @override
  int get hashCode =>
      songId.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      lrc.hashCode ^
      ttml.hashCode ^
      eslrc.hashCode ^
      qrc.hashCode ^
      yrc.hashCode ^
      lys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AllLyricsResponseForDart &&
          runtimeType == other.runtimeType &&
          songId == other.songId &&
          title == other.title &&
          artist == other.artist &&
          lrc == other.lrc &&
          ttml == other.ttml &&
          eslrc == other.eslrc &&
          qrc == other.qrc &&
          yrc == other.yrc &&
          lys == other.lys;
}

class SongPaginatedResponseForDart {
  final List<SongWithUrlForDart> data;
  final PlatformInt64 total;
  final int page;
  final int pageSize;
  final PlatformInt64 totalPages;

  const SongPaginatedResponseForDart({
    required this.data,
    required this.total,
    required this.page,
    required this.pageSize,
    required this.totalPages,
  });

  @override
  int get hashCode =>
      data.hashCode ^
      total.hashCode ^
      page.hashCode ^
      pageSize.hashCode ^
      totalPages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongPaginatedResponseForDart &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          total == other.total &&
          page == other.page &&
          pageSize == other.pageSize &&
          totalPages == other.totalPages;
}

class SongWithUrlForDart {
  final UuidValue id;
  final String title;
  final String path;
  final String? album;
  final String? artist;
  final String? coverPath;
  final String? coverUrl;

  const SongWithUrlForDart({
    required this.id,
    required this.title,
    required this.path,
    this.album,
    this.artist,
    this.coverPath,
    this.coverUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      path.hashCode ^
      album.hashCode ^
      artist.hashCode ^
      coverPath.hashCode ^
      coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongWithUrlForDart &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          path == other.path &&
          album == other.album &&
          artist == other.artist &&
          coverPath == other.coverPath &&
          coverUrl == other.coverUrl;
}
