// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'dict.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UpdateUserSettings`

Future<LoginResponse> userLoginForDart({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiWifiApiUserUserLoginForDart(
  username: username,
  password: password,
);

Future<UserSettings> getUserSettingsForDart() =>
    RustLib.instance.api.crateApiWifiApiUserGetUserSettingsForDart();

Future<UserSettings> updateUserSettingsForDart({
  String? language,
  String? flutterTheme,
}) => RustLib.instance.api.crateApiWifiApiUserUpdateUserSettingsForDart(
  language: language,
  flutterTheme: flutterTheme,
);

class LoginResponse {
  final String token;
  final String tokenType;

  const LoginResponse({required this.token, required this.tokenType});

  @override
  int get hashCode => token.hashCode ^ tokenType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginResponse &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          tokenType == other.tokenType;
}

class UserSettings {
  final String language;
  final String flutterTheme;

  const UserSettings({required this.language, required this.flutterTheme});

  @override
  int get hashCode => language.hashCode ^ flutterTheme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserSettings &&
          runtimeType == other.runtimeType &&
          language == other.language &&
          flutterTheme == other.flutterTheme;
}
