// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_dc_holder`, `shared_rt`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PeerListItem`, `SignalRequest`, `SignalResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`

/// 连接 WebRTC 信令并建立 DataChannel。
/// 消息通过 StreamSink 推送给 Dart。
Stream<String> connectWebrtc({required String deviceName}) => RustLib
    .instance
    .api
    .crateApiWifiApiWebrtcConnectWebrtc(deviceName: deviceName);

/// 通过 DataChannel 发送消息（JSON 字符串）
Future<void> sendWebrtcMessage({required String msg}) =>
    RustLib.instance.api.crateApiWifiApiWebrtcSendWebrtcMessage(msg: msg);
