// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 将字符串编码为 base64 格式
String base64EncodeWasm({required String input}) =>
    RustLib.instance.api.crateApiUtilsBase64Base64EncodeWasm(input: input);

/// 将 base64 编码的字符串解码为原始字符串
/// 如果解码失败，返回 None
String? base64DecodeWasm({required String input}) =>
    RustLib.instance.api.crateApiUtilsBase64Base64DecodeWasm(input: input);
