// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 加法运算
int add({required int a, required int b}) =>
    RustLib.instance.api.crateApiUtilsCalculatorAdd(a: a, b: b);

/// 加法运算（+22）
int add22({required int a, required int b}) =>
    RustLib.instance.api.crateApiUtilsCalculatorAdd22(a: a, b: b);

/// 乘法运算
int multiply({required int a, required int b}) =>
    RustLib.instance.api.crateApiUtilsCalculatorMultiply(a: a, b: b);
