// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<BigInt> decodeGifFrameCount({required String path}) =>
    RustLib.instance.api.crateApiUtilsGifDecodeDecodeGifFrameCount(path: path);

Future<GifFrame?> decodeGifFrame({
  required String path,
  required BigInt index,
}) => RustLib.instance.api.crateApiUtilsGifDecodeDecodeGifFrame(
  path: path,
  index: index,
);

Future<List<GifFrame>> decodeGifAllFrames({required String path}) =>
    RustLib.instance.api.crateApiUtilsGifDecodeDecodeGifAllFrames(path: path);

Future<List<GifFrameRgba>> decodeGifPreviewFrames({
  required String path,
  required BigInt maxFrames,
}) => RustLib.instance.api.crateApiUtilsGifDecodeDecodeGifPreviewFrames(
  path: path,
  maxFrames: maxFrames,
);

Stream<GifFrameRgba> decodeGifStream({
  required String path,
  required int maxFrames,
}) => RustLib.instance.api.crateApiUtilsGifDecodeDecodeGifStream(
  path: path,
  maxFrames: maxFrames,
);

class GifFrame {
  final Uint8List pngBytes;
  final int width;
  final int height;
  final int delayMs;

  const GifFrame({
    required this.pngBytes,
    required this.width,
    required this.height,
    required this.delayMs,
  });

  @override
  int get hashCode =>
      pngBytes.hashCode ^ width.hashCode ^ height.hashCode ^ delayMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GifFrame &&
          runtimeType == other.runtimeType &&
          pngBytes == other.pngBytes &&
          width == other.width &&
          height == other.height &&
          delayMs == other.delayMs;
}

class GifFrameRgba {
  final Uint8List rgba;
  final int width;
  final int height;
  final int delayMs;

  const GifFrameRgba({
    required this.rgba,
    required this.width,
    required this.height,
    required this.delayMs,
  });

  @override
  int get hashCode =>
      rgba.hashCode ^ width.hashCode ^ height.hashCode ^ delayMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GifFrameRgba &&
          runtimeType == other.runtimeType &&
          rgba == other.rgba &&
          width == other.width &&
          height == other.height &&
          delayMs == other.delayMs;
}
