// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 将时间戳转换为本地时间字符串
Future<String> timestampToLocal({required PlatformInt64 timestamp}) => RustLib
    .instance
    .api
    .crateApiUtilsTimestampTimestampToLocal(timestamp: timestamp);

/// 将时间戳转换为UTC时间字符串
Future<String> timestampToUtc({required PlatformInt64 timestamp}) => RustLib
    .instance
    .api
    .crateApiUtilsTimestampTimestampToUtc(timestamp: timestamp);

/// 将本地时间字符串转换为时间戳
Future<PlatformInt64?> localToTimestamp({required String timeStr}) => RustLib
    .instance
    .api
    .crateApiUtilsTimestampLocalToTimestamp(timeStr: timeStr);

/// 获取当前时间戳
Future<PlatformInt64> getCurrentTimestamp() =>
    RustLib.instance.api.crateApiUtilsTimestampGetCurrentTimestamp();

/// 获取当前本地时间字符串
Future<String> getCurrentLocalTime() =>
    RustLib.instance.api.crateApiUtilsTimestampGetCurrentLocalTime();

/// 获取当前UTC时间字符串
Future<String> getCurrentUtcTime() =>
    RustLib.instance.api.crateApiUtilsTimestampGetCurrentUtcTime();
