// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 生成UUID v4
Future<String> generateUuidV4() =>
    RustLib.instance.api.crateApiUtilsUuidGenerateUuidV4();

/// 生成UUID v5
Future<String> generateUuidV5({
  required String namespace,
  required String name,
}) => RustLib.instance.api.crateApiUtilsUuidGenerateUuidV5(
  namespace: namespace,
  name: name,
);

/// 生成UUID v6
Future<String> generateUuidV6() =>
    RustLib.instance.api.crateApiUtilsUuidGenerateUuidV6();

/// 生成UUID v7
Future<String> generateUuidV7() =>
    RustLib.instance.api.crateApiUtilsUuidGenerateUuidV7();

/// 验证UUID格式
Future<bool> validateUuid({required String uuidStr}) =>
    RustLib.instance.api.crateApiUtilsUuidValidateUuid(uuidStr: uuidStr);
