// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<double> luminance({required int r, required int g, required int b}) =>
    RustLib.instance.api.crateApiColorLuminance(r: r, g: g, b: b);

Future<double> contrastRatio({
  required (int, int, int) color1,
  required (int, int, int) color2,
}) => RustLib.instance.api.crateApiColorContrastRatio(
  color1: color1,
  color2: color2,
);

Future<int> colorToInt({
  required int r,
  required int g,
  required int b,
  required int a,
}) => RustLib.instance.api.crateApiColorColorToInt(r: r, g: g, b: b, a: a);

Future<bool> isVibrant({required int r, required int g, required int b}) =>
    RustLib.instance.api.crateApiColorIsVibrant(r: r, g: g, b: b);

Future<double> saturation({required int r, required int g, required int b}) =>
    RustLib.instance.api.crateApiColorSaturation(r: r, g: g, b: b);

Future<bool> isTooDark({required int r, required int g, required int b}) =>
    RustLib.instance.api.crateApiColorIsTooDark(r: r, g: g, b: b);

Future<double> colorDistance({
  required (int, int, int) c1,
  required (int, int, int) c2,
}) => RustLib.instance.api.crateApiColorColorDistance(c1: c1, c2: c2);

Future<bool> areColorsSimilar({
  required (int, int, int) c1,
  required (int, int, int) c2,
  required double threshold,
}) => RustLib.instance.api.crateApiColorAreColorsSimilar(
  c1: c1,
  c2: c2,
  threshold: threshold,
);

Future<Map<(int, int, int), BigInt>> mergeSimilarColors({
  required HashMapU8U8U8Usize colorCounts,
  required double threshold,
}) => RustLib.instance.api.crateApiColorMergeSimilarColors(
  colorCounts: colorCounts,
  threshold: threshold,
);

Future<(int, int, int)> invertColor({
  required int r,
  required int g,
  required int b,
}) => RustLib.instance.api.crateApiColorInvertColor(r: r, g: g, b: b);

Future<bool> isMonochromatic({
  required List<((int, int, int), BigInt)> colors,
  required BigInt totalPixels,
}) => RustLib.instance.api.crateApiColorIsMonochromatic(
  colors: colors,
  totalPixels: totalPixels,
);

Future<ColorInfo> extractColors({required List<int> imageData}) =>
    RustLib.instance.api.crateApiColorExtractColors(imageData: imageData);

Future<ColorInfo> extractColorsFromPath({required String imagePath}) => RustLib
    .instance
    .api
    .crateApiColorExtractColorsFromPath(imagePath: imagePath);

Future<List<ImageColorResult>> extractColorsFromPaths({
  required List<String> imagePaths,
}) => RustLib.instance.api.crateApiColorExtractColorsFromPaths(
  imagePaths: imagePaths,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< HashMap < (u8 , u8 , u8) , usize >>>
abstract class HashMapU8U8U8Usize implements RustOpaqueInterface {}

class ColorInfo {
  final int? backgroundColor;
  final int? secondaryColor;

  const ColorInfo({this.backgroundColor, this.secondaryColor});

  @override
  int get hashCode => backgroundColor.hashCode ^ secondaryColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorInfo &&
          runtimeType == other.runtimeType &&
          backgroundColor == other.backgroundColor &&
          secondaryColor == other.secondaryColor;
}

class ImageColorResult {
  final String name;
  final ColorInfo colorInfo;

  const ImageColorResult({required this.name, required this.colorInfo});

  @override
  int get hashCode => name.hashCode ^ colorInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageColorResult &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          colorInfo == other.colorInfo;
}
