// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool`, `run_migrations`, `simple_hash`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 初始化 / 打开 SQLite 数据库，返回是否为新创建
Future<bool> initDb({required String dbPath}) =>
    RustLib.instance.api.crateApiDbInitDb(dbPath: dbPath);

Future<void> kvSet({required String key, required String value}) =>
    RustLib.instance.api.crateApiDbKvSet(key: key, value: value);

Future<String?> kvGet({required String key}) =>
    RustLib.instance.api.crateApiDbKvGet(key: key);

Future<bool> kvDelete({required String key}) =>
    RustLib.instance.api.crateApiDbKvDelete(key: key);

Future<List<String>> kvKeys() => RustLib.instance.api.crateApiDbKvKeys();

Future<PlatformInt64?> kvGetInt({required String key}) =>
    RustLib.instance.api.crateApiDbKvGetInt(key: key);

Future<void> kvSetInt({required String key, required PlatformInt64 value}) =>
    RustLib.instance.api.crateApiDbKvSetInt(key: key, value: value);

Future<double?> kvGetDouble({required String key}) =>
    RustLib.instance.api.crateApiDbKvGetDouble(key: key);

Future<void> kvSetDouble({required String key, required double value}) =>
    RustLib.instance.api.crateApiDbKvSetDouble(key: key, value: value);

Future<void> kvJsonSet({required String key, required String json}) =>
    RustLib.instance.api.crateApiDbKvJsonSet(key: key, json: json);

Future<String?> kvJsonGet({required String key}) =>
    RustLib.instance.api.crateApiDbKvJsonGet(key: key);

Future<void> kvClear() => RustLib.instance.api.crateApiDbKvClear();

Future<List<LocalSong>> getLocalSongs() =>
    RustLib.instance.api.crateApiDbGetLocalSongs();

/// 扫描并导入歌曲：Rust 读元数据 + 保存封面 + 写入 SQLite
Future<List<LocalSong>> importLocalSongs({
  required List<String> paths,
  required String coversDir,
}) => RustLib.instance.api.crateApiDbImportLocalSongs(
  paths: paths,
  coversDir: coversDir,
);

Future<void> clearLocalSongs() =>
    RustLib.instance.api.crateApiDbClearLocalSongs();

class LocalSong {
  final String path;
  final String title;
  final String artist;
  final String album;
  final String duration;
  final String coverPath;
  final String albumId;
  final PlatformInt64 primaryColor;
  final PlatformInt64 secondaryColor;

  const LocalSong({
    required this.path,
    required this.title,
    required this.artist,
    required this.album,
    required this.duration,
    required this.coverPath,
    required this.albumId,
    required this.primaryColor,
    required this.secondaryColor,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      duration.hashCode ^
      coverPath.hashCode ^
      albumId.hashCode ^
      primaryColor.hashCode ^
      secondaryColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSong &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          duration == other.duration &&
          coverPath == other.coverPath &&
          albumId == other.albumId &&
          primaryColor == other.primaryColor &&
          secondaryColor == other.secondaryColor;
}
