// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> game2048New() => RustLib.instance.api.crateApiGamesGame2048New();

Future<Game2048State> game2048Get() =>
    RustLib.instance.api.crateApiGamesGame2048Get();

Future<Game2048State> game2048Move({required String dir}) =>
    RustLib.instance.api.crateApiGamesGame2048Move(dir: dir);

Future<Game2048State> game2048Undo() =>
    RustLib.instance.api.crateApiGamesGame2048Undo();

Future<bool> game2048CanMove({required String dir}) =>
    RustLib.instance.api.crateApiGamesGame2048CanMove(dir: dir);

Future<void> snakeNew() => RustLib.instance.api.crateApiGamesSnakeNew();

Future<SnakeState> snakeGet() => RustLib.instance.api.crateApiGamesSnakeGet();

Future<void> snakeSetDir({required String dir}) =>
    RustLib.instance.api.crateApiGamesSnakeSetDir(dir: dir);

Future<SnakeState> snakeTick() => RustLib.instance.api.crateApiGamesSnakeTick();

Future<void> minesweeperNew() =>
    RustLib.instance.api.crateApiGamesMinesweeperNew();

Future<MinesweeperState> minesweeperGet() =>
    RustLib.instance.api.crateApiGamesMinesweeperGet();

Future<MinesweeperState> minesweeperClick({
  required BigInt x,
  required BigInt y,
}) => RustLib.instance.api.crateApiGamesMinesweeperClick(x: x, y: y);

Future<MinesweeperState> minesweeperToggleFlag({
  required BigInt x,
  required BigInt y,
}) => RustLib.instance.api.crateApiGamesMinesweeperToggleFlag(x: x, y: y);

Future<void> tetrisNew() => RustLib.instance.api.crateApiGamesTetrisNew();

Future<TetrisState> tetrisGet() =>
    RustLib.instance.api.crateApiGamesTetrisGet();

Future<TetrisState> tetrisMove({required String dir}) =>
    RustLib.instance.api.crateApiGamesTetrisMove(dir: dir);

Future<TetrisState> tetrisTick() =>
    RustLib.instance.api.crateApiGamesTetrisTick();

class Game2048State {
  final Uint32List board;
  final BigInt score;
  final bool over;

  const Game2048State({
    required this.board,
    required this.score,
    required this.over,
  });

  @override
  int get hashCode => board.hashCode ^ score.hashCode ^ over.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Game2048State &&
          runtimeType == other.runtimeType &&
          board == other.board &&
          score == other.score &&
          over == other.over;
}

class MinesweeperState {
  final Uint8List cells;
  final List<bool> revealed;
  final List<bool> flagged;
  final bool over;
  final bool won;

  const MinesweeperState({
    required this.cells,
    required this.revealed,
    required this.flagged,
    required this.over,
    required this.won,
  });

  @override
  int get hashCode =>
      cells.hashCode ^
      revealed.hashCode ^
      flagged.hashCode ^
      over.hashCode ^
      won.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MinesweeperState &&
          runtimeType == other.runtimeType &&
          cells == other.cells &&
          revealed == other.revealed &&
          flagged == other.flagged &&
          over == other.over &&
          won == other.won;
}

class SnakeState {
  final Uint8List cells;
  final int score;
  final bool over;

  const SnakeState({
    required this.cells,
    required this.score,
    required this.over,
  });

  @override
  int get hashCode => cells.hashCode ^ score.hashCode ^ over.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnakeState &&
          runtimeType == other.runtimeType &&
          cells == other.cells &&
          score == other.score &&
          over == other.over;
}

class TetrisState {
  final Uint8List board;
  final int score;
  final bool over;

  const TetrisState({
    required this.board,
    required this.score,
    required this.over,
  });

  @override
  int get hashCode => board.hashCode ^ score.hashCode ^ over.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TetrisState &&
          runtimeType == other.runtimeType &&
          board == other.board &&
          score == other.score &&
          over == other.over;
}
