// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FRB 入口：native 走缓存，WASM 直接读
Future<AudioMetadata> readMetadata({required String filePath}) =>
    RustLib.instance.api.crateApiMetadataReadMetadata(filePath: filePath);

/// FRB 批量入口
Future<List<ResultAudioMetadataString>> readMetadataBatch({
  required List<String> filePaths,
}) => RustLib.instance.api.crateApiMetadataReadMetadataBatch(
  filePaths: filePaths,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioMetadata>>
abstract class AudioMetadata implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Result < AudioMetadata , String >>>
abstract class ResultAudioMetadataString implements RustOpaqueInterface {}
