// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'metadata.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base64_decode`, `base64_encode`

/// 带缓存的元数据读取，使用共享的 settings.db pool
Future<AudioMetadata> readMetadataCached({required String filePath}) => RustLib
    .instance
    .api
    .crateApiMusicCacheReadMetadataCached(filePath: filePath);
