// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 生成白噪音 PCM（f32，无缝循环）
Future<Float32List> whiteNoisePcm({
  required int durationMs,
  required int sampleRate,
  required int seed,
}) => RustLib.instance.api.crateApiNoiseWhiteNoisePcm(
  durationMs: durationMs,
  sampleRate: sampleRate,
  seed: seed,
);

/// 生成粉红噪音 PCM
Future<Float32List> pinkNoisePcm({
  required int durationMs,
  required int sampleRate,
  required int seed,
}) => RustLib.instance.api.crateApiNoisePinkNoisePcm(
  durationMs: durationMs,
  sampleRate: sampleRate,
  seed: seed,
);

/// 生成棕噪音 PCM
Future<Float32List> brownNoisePcm({
  required int durationMs,
  required int sampleRate,
  required int seed,
}) => RustLib.instance.api.crateApiNoiseBrownNoisePcm(
  durationMs: durationMs,
  sampleRate: sampleRate,
  seed: seed,
);

/// 生成雨声 PCM
Future<Float32List> rainNoisePcm({
  required int durationMs,
  required int sampleRate,
  required int seed,
}) => RustLib.instance.api.crateApiNoiseRainNoisePcm(
  durationMs: durationMs,
  sampleRate: sampleRate,
  seed: seed,
);
