// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 生字表：按年级/学期（grade 1-6，term 1-2）
Future<List<String>> ziciNewChars({required int grade, required int term}) =>
    RustLib.instance.api.crateApiZiciZiciNewChars(grade: grade, term: term);

/// 生词表：搜索（返回最多 500 个）
Future<List<String>> ziciNewWords({required String query}) =>
    RustLib.instance.api.crateApiZiciZiciNewWords(query: query);

Future<List<WordFrequencyEntry>> ziciWordFrequencySearch({
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiZiciZiciWordFrequencySearch(
  query: query,
  limit: limit,
);

/// 词频搜索（含释义）
class WordFrequencyEntry {
  final String word;
  final String pinyin;
  final int frequency;
  final String explanation;

  const WordFrequencyEntry({
    required this.word,
    required this.pinyin,
    required this.frequency,
    required this.explanation,
  });

  @override
  int get hashCode =>
      word.hashCode ^
      pinyin.hashCode ^
      frequency.hashCode ^
      explanation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordFrequencyEntry &&
          runtimeType == other.runtimeType &&
          word == other.word &&
          pinyin == other.pinyin &&
          frequency == other.frequency &&
          explanation == other.explanation;
}
