// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 按年级/学期返回生字表（grade 1-6，term 1-2）
Future<List<String>> ziciNewChars({required int grade, required int term}) =>
    RustLib.instance.api.crateApiZiciZiciNewChars(grade: grade, term: term);

/// 返回全部生词表（2182 个）
Future<List<String>> ziciNewWords() =>
    RustLib.instance.api.crateApiZiciZiciNewWords();

/// 词频搜索（首次调用解析 3.2MB json 并缓存）
Future<List<WordFrequencyEntry>> ziciWordFrequencySearch({
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiZiciZiciWordFrequencySearch(
  query: query,
  limit: limit,
);

/// 词频搜索（返回 word/pinyin/frequency/explanation）
class WordFrequencyEntry {
  final String word;
  final String pinyin;
  final int frequency;
  final String explanation;

  const WordFrequencyEntry({
    required this.word,
    required this.pinyin,
    required this.frequency,
    required this.explanation,
  });

  @override
  int get hashCode =>
      word.hashCode ^
      pinyin.hashCode ^
      frequency.hashCode ^
      explanation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordFrequencyEntry &&
          runtimeType == other.runtimeType &&
          word == other.word &&
          pinyin == other.pinyin &&
          frequency == other.frequency &&
          explanation == other.explanation;
}
