// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 按年级/学期返回生字表（grade 1-6，term 1-2）
Future<List<String>> ziciNewChars({required int grade, required int term}) =>
    RustLib.instance.api.crateApiZiciZiciNewChars(grade: grade, term: term);

/// 返回全部生词表（2182 个）
Future<List<String>> ziciNewWords() =>
    RustLib.instance.api.crateApiZiciZiciNewWords();
